import time
import behaviour.basic_actions as basic_action
import behaviour.intermidiate_actions as inter_action
import behaviour.advanced_actions as advanced_action


def run_tutorial(driver):
    basic_action.cookies_accept(driver)
    basic_action.close_ika_ads(driver)
    basic_action.tutorial_ok_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.set_sawmill_workers(driver,20)
    time.sleep(0.5)
    basic_action.city_view(driver)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.build(driver, 'academy')
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    inter_action.speedup_build_time(driver, 'academy')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'academy')
    basic_action.tutorial_reward_btn(driver)
    time.sleep(0.1)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    # research
    advanced_action.make_reserach(driver,1,1)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    time.sleep(0.5)
    advanced_action.set_scientist(driver, 8)
    basic_action.tutorial_reward_btn(driver)
    time.sleep(0.5)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    # warehouse
    advanced_action.build_warehouse(driver, 7) # first warehouse
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'warehouse')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'warehouse')
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    time.sleep(0.5)
    advanced_action.build(driver, 'barracks')
    time.sleep(0.5)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'barracks')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'barracks')
    time.sleep(0.5)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.recruit_army(driver, 1, 3)
    time.sleep(0.5)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.build(driver, 'wall')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'wall')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'wall')
    time.sleep(0.5)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.build(driver, 'port')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'port')
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'port')
    time.sleep(0.5)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    time.sleep(0.5)
    inter_action.speedup_build_time(driver, 'port')
    time.sleep(1)
    inter_action.speedup_build_time(driver, 'port')
    time.sleep(0.5)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.buy_cargo_ship(driver)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.upgrade(driver,'warehouse')
    basic_action.tutorial_reward_btn(driver)
    inter_action.close_building_window(driver,'warehouse')
    basic_action.tutorial_popup(driver)
    time.sleep(0.1)
    basic_action.tutorial_ok_btn(driver)
    advanced_action.attack_barbarians(driver,2, spearman=6)
    basic_action.tutorial_reward_btn(driver)
    basic_action.tutorial_popup(driver)
    basic_action.tutorial_ok_btn(driver)
    basic_action.ambrosia_shop(driver)
    basic_action.tutorial_reward_btn(driver)
    basic_action.city_view(driver)
    return True
